#!/usr/bin/env python3
"""
Battery Health & Analytics Dashboard - Flask Server
===================================================
Web application to run battery health report command, parse historical & live
battery statistics, and render an interactive modern dashboard.
"""

import csv
import io
import json
import os
import sys
from pathlib import Path
from flask import Flask, jsonify, render_template, request, Response, send_file

from battery_parser import (
    generate_and_parse_report,
    get_live_battery_status,
    load_html,
    parse_battery_report,
    generate_battery_report
)

app = Flask(__name__, static_folder="static", template_folder="templates")
REPORT_PATH = Path("battery-report.html").resolve()

# Cache parsed report in memory for fast serving
_cached_report = None


def get_or_create_report_data(force_generate: bool = False):
    """Retrieve cached battery data or generate/parse fresh report."""
    global _cached_report
    if force_generate or _cached_report is None:
        _cached_report = generate_and_parse_report(REPORT_PATH)
    else:
        # Always attach current live status on every request
        _cached_report["live_status"] = get_live_battery_status()
    return _cached_report


@app.route("/")
def index():
    """Main dashboard page."""
    try:
        data = get_or_create_report_data(force_generate=False)
    except Exception as e:
        data = {
            "error": str(e),
            "system_info": {},
            "battery": {"health_percent": None, "verdict": {}},
            "live_status": get_live_battery_status()
        }
    return render_template("index.html", initial_data=data)


@app.route("/api/battery-data", methods=["GET"])
def api_battery_data():
    """API endpoint returning complete battery health and usage analytics."""
    try:
        force = request.args.get("refresh", "0") in ("1", "true", "True")
        data = get_or_create_report_data(force_generate=force)
        return jsonify({"success": True, "data": data})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route("/api/generate-report", methods=["POST", "GET"])
def api_generate_report():
    """API endpoint to trigger a fresh powercfg /batteryreport execution."""
    global _cached_report
    try:
        _cached_report = generate_and_parse_report(REPORT_PATH)
        return jsonify({
            "success": True,
            "message": "Fresh battery report generated successfully.",
            "data": _cached_report
        })
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route("/api/live-status", methods=["GET"])
def api_live_status():
    """Fast polling endpoint for real-time battery status widget."""
    try:
        live = get_live_battery_status()
        return jsonify({"success": True, "live": live})
    except Exception as e:
        return jsonify({"success": False, "error": str(e)}), 500


@app.route("/api/export/json", methods=["GET"])
def export_json():
    """Export the battery report summary and metrics as downloadable JSON."""
    try:
        data = get_or_create_report_data(force_generate=False)
        json_str = json.dumps(data, indent=2, ensure_ascii=False)
        return Response(
            json_str,
            mimetype="application/json",
            headers={"Content-Disposition": "attachment;filename=battery_health_report.json"}
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/export/csv", methods=["GET"])
def export_csv():
    """Export capacity history and daily usage breakdown as CSV."""
    try:
        data = get_or_create_report_data(force_generate=False)
        history = data.get("capacity_history", [])
        output = io.StringIO()
        if history:
            fieldnames = list(history[0].keys())
            writer = csv.DictWriter(output, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(history)
        else:
            output.write("No capacity history data available\n")

        output.seek(0)
        return Response(
            output.getvalue(),
            mimetype="text/csv",
            headers={"Content-Disposition": "attachment;filename=battery_capacity_history.csv"}
        )
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/raw-report")
def raw_report():
    """Serve the raw original HTML report generated by Windows."""
    if REPORT_PATH.exists():
        return send_file(REPORT_PATH, mimetype="text/html")
    return "No raw battery report found. Please generate one first.", 404


if __name__ == "__main__":
    if sys.platform == "win32":
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass

    # Ensure a fresh report exists on launch
    try:
        print("[VoltPulse] Initializing Battery Health Report...")
        get_or_create_report_data(force_generate=True)
        print("[VoltPulse] Battery report loaded successfully!")
    except Exception as e:
        print(f"[VoltPulse] Warning during initial battery report generation: {e}")

    host = "127.0.0.1"
    port = 5000
    print(f"\n=======================================================")
    print(f"  VoltPulse Battery Dashboard: http://{host}:{port}/")
    print(f"=======================================================\n")
    app.run(host=host, port=port, debug=False)

